name: push-main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run the tests
        run: |
          chmod +x gradlew
          ./gradlew test 
