name: push-main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install deps
        run: |
          pip3 install -r requirements-dev.txt

      - name: Run tests
        run: make test
